app:
  image:
    tag: "1.2.3"
  svc:
    audience: svc.test.net
    credentials:
      svc-pkcs8-der-credentials:
        - subPath: svc.private_key
          mountPath: /app/data/keys/svc.private_key.p8.der
  audiences:
    - audience: foo.bar
      credentials:
        foxford-pkcs8-der-credentials:
          - subPath: iam.foo.public_key
            mountPath: /app/data/keys/iam.foo.public_key.p8.der
      authn:
        key: /app/data/keys/iam.foo.public_key.p8.der
      authz:
        type: http
ingress:
  hosts:
    - foo.bar
    - bar.foo
