# Default values for nats-gatekeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

container:
  image:
    repository: foxford/nats-gatekeeper
    tag: ""

  resources:
    limits:
      cpu: 0.5
      memory: 50Mi
    requests:
      cpu: 0.5
      memory: 50Mi

svc:
  audience: svc.services
  credentials:
    - secret: svc-secret
      subPath: private-key
      mountPath: /path/to/svc/private/key

audiences:
  - audience: foo.bar
    credentials:
      - secret: foobar-der-credentials
        subPath: foobar-public-key
        mountPath: /path/to/foobar/public/key
    authn:
      key: path/to/public_key.p8.der
    authz:
      type: http
      url: "https://authz.example.org/api/v1/authz"

config:
  expiration: 16 hours
  max_subscriptions: 5
  max_payload: 102400

env:
  RUST_LOG: warn,nats_gatekeeper=info,svc_utils=info,svc_utils::metrics=warn

service:
  type: ClusterIP
  ports:
    http: 8080
    metrics: 8081

ingress:
  host: foo.bar.example
  tls:
    secretName: tls-certificates
