# Default values for nats-gatekeeper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

minReadySeconds: 5
preStopSleepSeconds: 5

app:
  image:
    repository: cr.yandex/crp1of6bddata8ain3q5/nats-gatekeeper

  resources:
    requests:
      cpu: 0.01
      memory: 50Mi
    limits:
      memory: 100Mi

  natsTokenClaims:
    expiration: 16 hours
    max_subscriptions: 5
    max_payload: 10240 # 10KB

env:
  RUST_LOG: warn,nats_gatekeeper=info,svc_utils=info,svc_utils::metrics=warn

clusterService:
  ports:
    http: 8080
    metrics: 8888

tls:
  secretName: tls-certificates

serviceMonitor:
  labels:
    release: kube-prometheus-stack

ingress:
  class: nginx
