apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "nats-gatekeeper.labels" . | nindent 4 }}
  name: {{ include "nats-gatekeeper.fullname" . }}-app
data:
  App.toml: |
    {{- $id := list (include "nats-gatekeeper.name" . ) .Values.app.svc.audience | compact | join "." }}
    id = {{ $id | quote }}

    http_addr = "0.0.0.0:8080"

    expiration = {{ .Values.app.natsTokenClaims.expiration | quote }}
    max_subscriptions = {{ .Values.app.natsTokenClaims.max_subscriptions }}
    max_payload = {{ .Values.app.natsTokenClaims.max_payload }}


    [metrics.http]
    bind_address = "0.0.0.0:8888"

    {{- println "" }}

    {{- range .Values.app.audiences }}
    ##
    ## {{ .audience }}
    ##
    {{- $tenantServiceAudience := include "nats-gatekeeper.tenantServiceAudience" .audience }}
    {{- $tenantUserAudience := include "nats-gatekeeper.tenantUserAudience" .audience }}
    {{- $tenantObjectAudience := include "nats-gatekeeper.tenantObjectAudience" (list $.Release.Namespace .audience) }}
    {{- with "authn" | get . }}
    [authn.{{ list "iam" $tenantServiceAudience | join "." | quote }}]
    audience = [{{ $tenantServiceAudience | quote }}, {{ $tenantUserAudience | quote }}]
    algorithm = "ES256"
    key = {{ "key" | get . | quote }}
    {{- end }}

    {{- println "" }}

    {{- with "authz" | get . }}
    [authz.{{ $tenantObjectAudience | quote }}]
    type = {{ .type | quote }}
    {{- if eq "http" .type }}
    uri = {{ list "http://dispatcher-cluster:8080/api/v1/authz/" $tenantObjectAudience | join "" | default .uri | quote }}
    algorithm = {{ default "ES256" .algorithm | quote }}
    key = {{ default "data/keys/svc.private_key.p8.der" .key | quote }}
    user_agent = {{ default $id .user_agent | quote }}
    max_retries = {{ default 3 .max_retries }}
    {{- end}}
    {{- end }}
    {{- println "" }}
    {{- end }}
