apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nats-gatekeeper.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ include "nats-gatekeeper.ingressPath" . }}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "nats-gatekeeper.fullname" $ }}-cluster
                port:
                  number: {{ get .Values.clusterService.ports "http" }}
